import React, { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

const translations = {
  en: {
    // Sidebar
    nav_dashboard: "Dashboard",
    nav_my_farm: "My Farm",
    nav_portfolio: "Farm Portfolio",
    nav_planner: "Planner",
    nav_crop_intelligence: "Crop Intelligence",
    nav_soil_analyzer: "Soil Analyzer",
    nav_disease_detection: "Disease Detection",
    nav_crop_recommendations: "Crop Recommendations",
    nav_insights: "Insights",
    nav_market_intelligence: "Market Intelligence",
    nav_yield_prediction: "Yield Prediction",
    nav_analytics: "Analytics",
    nav_ai_assistant: "AI Assistant",
    nav_virtual_agronomist: "Virtual Agronomist",
    nav_notifications: "Notifications",
    nav_settings: "Settings",
    nav_help: "Help",
    nav_logout: "Logout",
    nav_active_farm: "Active Farm",
    nav_risk_warnings: "Risk Intelligence",

    // Dashboard
    db_welcome: "Namaste",
    db_farm_overview: "Farm Overview",
    db_weather: "Current Weather",
    db_soil_health: "Soil Health Score",
    db_today_alerts: "Today's Alerts",
    db_today_recommendation: "Today's Recommendation",
    db_nitrogen_low: "Nitrogen is slightly low.",
    db_recommended_crop: "Recommended Crop",
    db_expected_yield: "Expected Yield",
    db_view_details: "View Details",
    db_quick_actions: "Quick Actions",
    db_recent_activity: "Recent Activity",
    db_latest_soil_test: "Latest soil test",
    db_recent_disease_scan: "Recent disease scan",
    db_planner_reminders: "Planner reminders",
    db_market_alerts: "Market alerts",
    db_small_analytics: "Key Metrics",
    db_total_area: "Total Area",
    db_health_score: "Health Score",
    db_expected_profit: "Expected Profit",
    db_active_alerts: "Active Alerts",

    // Quick Actions
    action_analyze_soil: "Analyze Soil",
    action_detect_disease: "Detect Disease",
    action_ask_ai: "Ask AI",
    action_view_prices: "View Market Prices",
    action_predict_yield: "Predict Yield",
    action_view_analytics: "View Analytics",

    // Common Buttons / Labels
    btn_open: "Open →",
    btn_submit: "Submit",
    btn_cancel: "Cancel",
    btn_save: "Save Settings",
    btn_loading: "Loading...",
    btn_add_farm: "Add New Farm",
    btn_export_pdf: "Export PDF Report",

    // Form fields
    form_crop_planned: "Planned Crop",
    form_nitrogen: "Nitrogen (N) level",
    form_phosphorus: "Phosphorus (P) level",
    form_potassium: "Potassium (K) level",
    form_ph: "pH level",
    form_location: "Location",
    form_farm_name: "Farm Name",
    form_farm_area: "Total Area (Acres)",

    // Placeholders & Statuses
    status_healthy: "Healthy",
    status_warning: "Warning",
    status_critical: "Critical",
    status_connected: "Connected",
    status_unconfigured: "Unconfigured",
    msg_no_data: "No data available.",
    dis_symptoms: "Symptoms Observed",
    dis_chemical_treatment: "Chemical / Standard Treatments",
    dis_organic_treatment: "Organic Treatments",
    dis_preventive_measures: "Preventive Actions",
    dis_recovery_steps: "Recovery Steps",
    soil_analyzer_title: "Soil Diagnostics & Recommendations",
    soil_log_test: "Log Soil Test",
    soil_test_records: "Test Records",
    soil_no_tests: "No logged soil tests yet.",
    soil_pending_ai: "Pending AI",
    soil_analyzed: "Analyzed",
    soil_tested_on: "Tested on",
    soil_no_report_selected: "No Report Selected",
    soil_select_report_desc: "Select a logged test report on the left or create a new test log.",
    soil_delete: "Delete",
    soil_ph_level: "pH Level",
    soil_nitrogen: "Nitrogen (N)",
    soil_phosphorus: "Phosphorus (P)",
    soil_potassium: "Potassium (K)",
    soil_organic_matter: "Organic Matter",
    soil_mg_kg: "mg/kg",
    soil_optional: "Optional",
    soil_testing_date: "Testing Date",
    soil_om_missing_explanation: "Organic Matter measurements were not provided in this test report. Soil diagnosis and fertilizer advice have been calculated based on the available metrics (pH, Nitrogen, Phosphorus, Potassium).",
    soil_err_ph: "Soil pH must be between 0.0 and 14.0.",
    soil_err_negative: "Nutrient values cannot be negative.",
    soil_err_om_pct: "Organic matter must be a percentage between 0% and 100%.",
    soil_err_save: "Failed to log soil report. Please check your values.",
    soil_na: "N/A",
    soil_ai_analysis_title: "AI Agronomist Analysis",
    soil_diagnostics_summary: "Diagnostics Summary",
    soil_nitrogen_advice: "Nitrogen Advice",
    soil_phosphorus_advice: "Phosphorus Advice",
    soil_potassium_advice: "Potassium Advice",
    soil_organic_matter_advice: "Organic Matter Advice",
    soil_treatment_schedule: "Recommended Treatment Schedule",
    soil_ai_pending_title: "AI Recommendation Pending",
    soil_ai_pending_desc: "Get expert AI agronomist suggestions for crop-planned soil fertilizers, mineral balances, and a feeding schedule.",
    soil_generate_btn: "Generate AI Assessment",
    soil_generating_btn: "Analyzing Metrics...",
    help_title: "Help & Documentation Center",
    help_subtitle: "Guides, frequently asked questions, and platform troubleshooting instructions",
    help_search: "Search guides, FAQs, or troubleshooting tips...",
    help_guides_title: "Platform Operations Guides",
    help_no_guides: "No guides match your search.",
    help_guide_suffix: "Guide",
    help_faqs_title: "Frequently Asked Questions",
    help_no_faqs: "No FAQs match your search.",
    help_troubleshoot: "Troubleshooting",
    help_support_title: "Need Contact Support?",
    help_support_desc: "Our agronomist support desk is available to answer complex soil, disease, or scheduling operations queries.",
    help_support_btn: "Contact support@agriassist.ai",
  },
  te: {
    // Sidebar
    nav_dashboard: "డాష్‌బోర్డ్",
    nav_my_farm: "నా ఫారమ్",
    nav_portfolio: "ఫారమ్ పోర్ట్‌ఫోలియో",
    nav_planner: "ప్రణాళికాకర్త (ప్లానర్)",
    nav_crop_intelligence: "పంట ఇంటెలిజెన్స్",
    nav_soil_analyzer: "నేల విశ్లేషణ",
    nav_disease_detection: "తెగులు గుర్తింపు",
    nav_crop_recommendations: "పంట సిఫార్సులు",
    nav_insights: "అవగాహనలు",
    nav_market_intelligence: "మార్కెట్ ధరలు",
    nav_yield_prediction: "దిగుబడి అంచనా",
    nav_analytics: "విశ్లేషణలు",
    nav_ai_assistant: "AI అసిస్టెంట్",
    nav_virtual_agronomist: "వర్చువల్ అగ్రోనమిస్ట్",
    nav_notifications: "నోటిఫికేషన్లు",
    nav_settings: "సెట్టింగులు",
    nav_help: "సహాయం",
    nav_logout: "లాగ్ అవుట్",
    nav_active_farm: "సక్రియ ఫారమ్",
    nav_risk_warnings: "రిస్క్ ఇంటెలిజెన్స్",

    // Dashboard
    db_welcome: "నమస్తే",
    db_farm_overview: "వ్యవసాయ అవలోకనం",
    db_weather: "ప్రస్తుత వాతావరణం",
    db_soil_health: "నేల ఆరోగ్య స్కోరు",
    db_today_alerts: "నేటి హెచ్చరికలు",
    db_today_recommendation: "నేటి AI సిఫార్సు",
    db_nitrogen_low: "నత్రజని (నైట్రోజन) కొద్దిగా తక్కువగా ఉంది.",
    db_recommended_crop: "సిఫార్సు చేయబడిన పంట",
    db_expected_yield: "ఆశించిన దిగుబడి",
    db_view_details: "వివరాలను వీక్షించండి",
    db_quick_actions: "త్వరిత చర్యలు",
    db_recent_activity: "ఇటీవలి కార్యాచరణ",
    db_latest_soil_test: "ఇటీవలి నేల పరీక్ష",
    db_recent_disease_scan: "ఇటీవలి తెగులు స్కాన్",
    db_planner_reminders: "ప్లానర్ రిమైండర్లు",
    db_market_alerts: "మార్కెట్ హెచ్చరికలు",
    db_small_analytics: "కీలక కొలమానాలు",
    db_total_area: "మొత్తం వైశాల్యం",
    db_health_score: "ఆరోగ్య స్కోరు",
    db_expected_profit: "ఆశించిన లాభం",
    db_active_alerts: "సక్రియ హెచ్చరికలు",

    // Quick Actions
    action_analyze_soil: "నేలను పరీక్షించండి",
    action_detect_disease: "తెగులు గుర్తించండి",
    action_ask_ai: "AI ని అడగండి",
    action_view_prices: "మార్కెట్ ధరలు",
    action_predict_yield: "దిగుబడి అంచనా",
    action_view_analytics: "విశ్లేషణలు",

    // Common Buttons / Labels
    btn_open: "ఓపెన్ చేయండి →",
    btn_submit: "సమర్పించు",
    btn_cancel: "రద్దు చేయి",
    btn_save: "సెట్టింగులు సేవ్ చేయి",
    btn_loading: "నమోదవుతోంది...",
    btn_add_farm: "కొత్త ఫారమ్ జోడించండి",
    btn_export_pdf: "PDF రిపోర్ट డౌన్‌లోడ్",

    // Form fields
    form_crop_planned: "ప్లాన్ చేసిన పంట",
    form_nitrogen: "నత్రజని (N) స్థాయి",
    form_phosphorus: "భాస్వరం (P) స్థాయి",
    form_potassium: "పोटాషియం (K) స్థాయి",
    form_ph: "pH స్థాయి",
    form_location: "స్థానం",
    form_farm_name: "ఫారమ్ పేరు",
    form_farm_area: "మొత్తం వైశాల్యం (ఎకరాలు)",

    // Placeholders & Statuses
    status_healthy: "ఆరోగ్యకరమైనది",
    status_warning: "హెచ్చరిక",
    status_critical: "తీవ్రమైనది",
    status_connected: "కనెక్ట్ అయింది",
    status_unconfigured: "కాన్ఫిగర్ చేయలేదు",
    msg_no_data: "సмаచారం అందుబాటులో లేదు.",
    dis_symptoms: "గమనించిన లక్షణాలు",
    dis_chemical_treatment: "రసాయన / సాధారణ చికిత్సలు",
    dis_organic_treatment: "సేంద్రీయ చికిత్సలు (ఆర్గానిక్)",
    dis_preventive_measures: "నివారణ చర్యలు",
    dis_recovery_steps: "కోలుకునే మార్గాలు (రికవరీ)",
    soil_analyzer_title: "నేల నిర్ధారణ & సిఫార్సులు",
    soil_log_test: "నేల పరీక్ష నమోదు చేయండి",
    soil_test_records: "పరీక్ష రికార్డులు",
    soil_no_tests: "ఇంకా నేల పరీక్షలు నమోదు చేయలేదు.",
    soil_pending_ai: "AI పెండింగ్",
    soil_analyzed: "విశ్లేషించబడింది",
    soil_tested_on: "పరీక్షించిన తేదీ",
    soil_no_report_selected: "ఏ రిపోర్టు ఎంపిక చేయలేదు",
    soil_select_report_desc: "ఎడమ వైపున ఉన్న రిపోర్టును ఎంచుకోండి లేదా కొత్త పరీక్షను నమోదు చేయండి.",
    soil_delete: "తొలగించు",
    soil_ph_level: "pH స్థాయి",
    soil_nitrogen: "నత్రజని (N)",
    soil_phosphorus: "భాస్వరం (P)",
    soil_potassium: "పొటాషియం (K)",
    soil_organic_matter: "సేంద్రీయ పదార్థం",
    soil_mg_kg: "మిల్లీగ్రాము/కిలో",
    soil_optional: "ఐచ్ఛికం",
    soil_testing_date: "పరీక్ష తేదీ",
    soil_om_missing_explanation: "ఈ పరీక్ష నివేదికలో సేంద్రీయ పదార్థ కొలతలు అందించబడలేదు. అందుబాటులో ఉన్న కొలతలు (pH, నత్రజని, భాస్వరం, పొటాషియం) ఆధారంగా నేల నిర్ధారణ మరియు ఎరువుల సలహా లెక్కించబడ్డాయి.",
    soil_err_ph: "నేల pH విలువ 0.0 మరియు 14.0 మధ్య ఉండాలి.",
    soil_err_negative: "పోషకాల విలువలు రుణాత్మకంగా ఉండకూడదు.",
    soil_err_om_pct: "సేంద్రీయ పదార్థం 0% మరియు 100% మధ్య శాతంగా ఉండాలి.",
    soil_err_save: "నేల నివేదికను నమోదు చేయడంలో విఫలమైంది. దయచేసి మీ విలువలను తనిఖీ చేయండి.",
    soil_na: "అందుబాటులో లేదు",
    soil_ai_analysis_title: "AI అగ్రోనమిస్ట్ విశ్లేషణ",
    soil_diagnostics_summary: "రోగనిర్ధారణ సారాంశం",
    soil_nitrogen_advice: "నత్రజని సలహా",
    soil_phosphorus_advice: "భాస్వరం సలహా",
    soil_potassium_advice: "పొటాషియం సలహా",
    soil_organic_matter_advice: "సేంద్రీయ పదార్థం సలహా",
    soil_treatment_schedule: "సిఫార్సు చేసిన చికిత్సల షెడ్యూల్",
    soil_ai_pending_title: "AI సిఫార్సు పెండింగ్‌లో ఉంది",
    soil_ai_pending_desc: "పంటకు అవసరమైన నేల ఎరువులు, ఖనిజ సమతుల్యత మరియు ఫీడింగ్ షెడ్యూల్ కోసం నిపుణులైన AI అగ్రోనమిస్ట్ సూచనలను పొందండి.",
    soil_generate_btn: "AI అంచనాను రూపొందించండి",
    soil_generating_btn: "కొలతలను విశ్లేషిస్తోంది...",
    help_title: "సహాయం & డాక్యుమెంటేషన్ కేంద్రం",
    help_subtitle: "మార్గదర్శకాలు, తరచుగా అడిగే ప్రశ్నలు మరియు ప్లాట్‌ఫారమ్ ట్రబుల్‌షూటింగ్ సూచనలు",
    help_search: "మార్గదర్శకాలు, తరచుగా అడిగే ప్రశ్నలు లేదా ట్రబుల్‌షూటింగ్ చిట్కాలను శోధించండి...",
    help_guides_title: "ప్లాట్‌ఫారమ్ ఆపరేషన్స్ గైడ్‌లు",
    help_no_guides: "మీ శోధనకు సరిపోయే మార్గదర్శకాలు లేవు.",
    help_guide_suffix: "గైడ్",
    help_faqs_title: "తరచుగా అడిగే ప్రశ్నలు",
    help_no_faqs: "మీ శోధనకు సరిపోయే ప్రశ్నలు లేవు.",
    help_troubleshoot: "ట్రబుల్‌షూటింగ్",
    help_support_title: "మద్దతు కోసం సంప్రదించాలా?",
    help_support_desc: "సంక్లిష్టమైన నేల, వ్యాధి లేదా షెడ్యూలింగ్ ప్రశ్నలకు సమాధానమివ్వడానికి మా వ్యవసాయ శాస్త్రవేత్తల బృందం అందుబాటులో ఉంది.",
    help_support_btn: "support@agriassist.aiని సంప్రదించండి",
  },
  hi: {
    // Sidebar
    nav_dashboard: "डैशबोर्ड",
    nav_my_farm: "मेरा खेत",
    nav_portfolio: "खेत पोर्टफोलियो",
    nav_planner: "योजनाकार (प्लानर)",
    nav_crop_intelligence: "फसल इंटेलिजेंस",
    nav_soil_analyzer: "मिट्टी विश्लेषक",
    nav_disease_detection: "रोग पहचान",
    nav_crop_recommendations: "फसल अनुशंसाएं",
    nav_insights: "अंतर्दृष्टि",
    nav_market_intelligence: "बाजार मूल्य",
    nav_yield_prediction: "उपज का अनुमान",
    nav_analytics: "विश्लेषण",
    nav_ai_assistant: "AI सहायक",
    nav_virtual_agronomist: "आभासी कृषि वैज्ञानिक",
    nav_notifications: "सूचनाएं",
    nav_settings: "सेटिंग्स",
    nav_help: "सहायता",
    nav_logout: "लॉग आउट",
    nav_active_farm: "सक्रिय खेत",
    nav_risk_warnings: "जोखिम खुफिया",

    // Dashboard
    db_welcome: "नमस्ते",
    db_farm_overview: "खेत का अवलोकन",
    db_weather: "वर्तमान मौसम",
    db_soil_health: "मिट्टी स्वास्थ्य स्कोर",
    db_today_alerts: "आज के अलर्ट",
    db_today_recommendation: "आज की अनुशंसा",
    db_nitrogen_low: "नाइट्रोजन का स्तर थोड़ा कम है।",
    db_recommended_crop: "अनुशंसित फसल",
    db_expected_yield: "अपेक्षित उपज",
    db_view_details: "विवरण देखें",
    db_quick_actions: "त्वरित कार्रवाई",
    db_recent_activity: "हाल की गतिविधि",
    db_latest_soil_test: "हालिया मिट्टी परीक्षण",
    db_recent_disease_scan: "हालिया रोग स्कैन",
    db_planner_reminders: "प्लानर अनुस्मारक",
    db_market_alerts: "बाजार के अलर्ट",
    db_small_analytics: "प्रमुख डेटा",
    db_total_area: "कुल क्षेत्रफल",
    db_health_score: "स्वास्थ्य स्कोर",
    db_expected_profit: "अपेक्षित लाभ",
    db_active_alerts: "सक्रिय अलर्ट",

    // Quick Actions
    action_analyze_soil: "मिट्टी का परीक्षण",
    action_detect_disease: "रोग की पहचान",
    action_ask_ai: "AI से पूछें",
    action_view_prices: "बाजार दरें देखें",
    action_predict_yield: "उपज का अनुमान",
    action_view_analytics: "विश्लेषण देखें",

    // Common Buttons / Labels
    btn_open: "खोलें →",
    btn_submit: "जमा करें",
    btn_cancel: "रद्द करें",
    btn_save: "सेटिंग्स सहेजें",
    btn_loading: "लोड हो रहा है...",
    btn_add_farm: "नया खेत जोड़ें",
    btn_export_pdf: "PDF रिपोर्ट डाउनलोड करें",

    // Form fields
    form_crop_planned: "नियोजित फसल",
    form_nitrogen: "नाइट्रोजन (N) स्तर",
    form_phosphorus: "फास्फोरस (P) स्तर",
    form_potassium: "पोटेशियम (K) स्तर",
    form_ph: "pH स्तर",
    form_location: "स्थान",
    form_farm_name: "खेत का नाम",
    form_farm_area: "कुल क्षेत्रफल (एकड़)",

    // Placeholders & Statuses
    status_healthy: "स्वस्थ",
    status_warning: "चेतावनी",
    status_critical: "गंभीर",
    status_connected: "जुड़ा हुआ है",
    status_unconfigured: "कॉन्फ़िगर नहीं है",
    msg_no_data: "कोई डेटा उपलब्ध नहीं है.",
    dis_symptoms: "पाए गए लक्षण",
    dis_chemical_treatment: "रासायनिक / सामान्य उपचार",
    dis_organic_treatment: "जैविक उपचार (ऑर्गेनिक)",
    dis_preventive_measures: "निवारक उपाय",
    dis_recovery_steps: "रिकवरी चरण",
    soil_analyzer_title: "मिट्टी निदान एवं सिफारिशें",
    soil_log_test: "मिट्टी परीक्षण दर्ज करें",
    soil_test_records: "परीक्षण रिकॉर्ड",
    soil_no_tests: "अभी तक कोई मिट्टी परीक्षण दर्ज नहीं किया गया है।",
    soil_pending_ai: "AI लंबित",
    soil_analyzed: "विश्लेषण किया गया",
    soil_tested_on: "परीक्षण तिथि",
    soil_no_report_selected: "कोई रिपोर्ट चयनित नहीं है",
    soil_select_report_desc: "बाईं ओर से एक परीक्षण रिपोर्ट चुनें या नया परीक्षण दर्ज करें।",
    soil_delete: "हटाएं",
    soil_ph_level: "pH स्तर",
    soil_nitrogen: "नाइट्रोजन (N)",
    soil_phosphorus: "फास्फोरस (P)",
    soil_potassium: "पोटेशियम (K)",
    soil_organic_matter: "कार्बनिक पदार्थ",
    soil_mg_kg: "मिग्रा/किग्रा",
    soil_optional: "वैकल्पिक",
    soil_testing_date: "परीक्षण तिथि",
    soil_om_missing_explanation: "इस परीक्षण रिपोर्ट में कार्बनिक पदार्थ का माप प्रदान नहीं किया गया था। उपलब्ध मापदंडों (pH, नाइट्रोजन, फास्फोरस, पोटेशियम) के आधार पर मिट्टी के निदान और उर्वरक सलाह की गणना की गई है।",
    soil_err_ph: "मिट्टी का पीएच मान 0.0 और 14.0 के बीच होना चाहिए।",
    soil_err_negative: "पोषक तत्वों का मूल्य नकारात्मक नहीं हो सकता।",
    soil_err_om_pct: "कार्बनिक पदार्थ 0% और 100% के बीच एक प्रतिशत होना चाहिए।",
    soil_err_save: "मिट्टी की रिपोर्ट दर्ज करने में विफल। कृपया अपने मानों की जाँच करें।",
    soil_na: "लागू नहीं",
    soil_ai_analysis_title: "AI कृषि वैज्ञानिक विश्लेषण",
    soil_diagnostics_summary: "निदान सारांश",
    soil_nitrogen_advice: "नाइट्रोजन सलाह",
    soil_phosphorus_advice: "फास्फोरस सलाह",
    soil_potassium_advice: "पोटेशियम सलाह",
    soil_organic_matter_advice: "कार्बनिक पदार्थ सलाह",
    soil_treatment_schedule: "अनुशंसित उपचार कार्यक्रम",
    soil_ai_pending_title: "AI सिफारिश लंबित",
    soil_ai_pending_desc: "फसल-नियोजित मिट्टी उर्वरकों, खनिज संतुलन और उपचार कार्यक्रम के लिए विशेषज्ञ AI कृषि वैज्ञानिक के सुझाव प्राप्त करें।",
    soil_generate_btn: "AI मूल्यांकन उत्पन्न करें",
    soil_generating_btn: "मापदंडों का विश्लेषण...",
    help_title: "सहायता एवं दस्तावेज़ीकरण केंद्र",
    help_subtitle: "गाइड, अक्सर पूछे जाने वाले प्रश्न और प्लेटफ़ॉर्म समस्या निवारण निर्देश",
    help_search: "गाइड, अक्सर पूछे जाने वाले प्रश्न या समस्या निवारण युक्तियाँ खोजें...",
    help_guides_title: "प्लेटफ़ॉर्म संचालन गाइड",
    help_no_guides: "आपकी खोज से मेल खाने वाला कोई गाइड नहीं है।",
    help_guide_suffix: "गाइड",
    help_faqs_title: "अक्सर पूछे जाने वाले प्रश्न",
    help_no_faqs: "आपकी खोज से मेल खाने वाले कोई प्रश्न नहीं हैं।",
    help_troubleshoot: "समस्या निवारण",
    help_support_title: "मदद की ज़रूरत है?",
    help_support_desc: "जटिल मिट्टी, बीमारी या शेड्यूलिंग प्रश्नों के उत्तर देने के लिए हमारी कृषि वैज्ञानिक सहायता टीम उपलब्ध है।",
    help_support_btn: "support@agriassist.ai से संपर्क करें",
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("agri_lang") || "en";
  });

  useEffect(() => {
    localStorage.setItem("agri_lang", language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations["en"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
