"""add market intelligence tables

Revision ID: 2cb8b4817ecb
Revises: 71a6b6e3b37d
Create Date: 2026-06-12 13:53:17.501757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb8b4817ecb'
down_revision: Union[str, Sequence[str], None] = '71a6b6e3b37d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(length=150), nullable=False),
    sa.Column('market_name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_prices_crop_name'), 'market_prices', ['crop_name'], unique=False)
    op.create_index(op.f('ix_market_prices_id'), 'market_prices', ['id'], unique=False)
    op.create_index(op.f('ix_market_prices_recorded_date'), 'market_prices', ['recorded_date'], unique=False)
    op.create_table('profitability_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(length=150), nullable=False),
    sa.Column('expected_yield', sa.Float(), nullable=False),
    sa.Column('cultivation_cost', sa.Float(), nullable=False),
    sa.Column('market_price_per_kg', sa.Float(), nullable=False),
    sa.Column('estimated_revenue', sa.Float(), nullable=False),
    sa.Column('estimated_profit', sa.Float(), nullable=False),
    sa.Column('profit_margin', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profitability_analyses_created_at'), 'profitability_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_profitability_analyses_id'), 'profitability_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profitability_analyses_id'), table_name='profitability_analyses')
    op.drop_index(op.f('ix_profitability_analyses_created_at'), table_name='profitability_analyses')
    op.drop_table('profitability_analyses')
    op.drop_index(op.f('ix_market_prices_recorded_date'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_id'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_crop_name'), table_name='market_prices')
    op.drop_table('market_prices')
    # ### end Alembic commands ###
