"""add_farm_analytics_snapshots

Revision ID: 3e3946b0e136
Revises: 549651001f81
Create Date: 2026-06-13 07:03:58.415124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3946b0e136'
down_revision: Union[str, Sequence[str], None] = '549651001f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_analytics_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('projected_profit', sa.Float(), nullable=False),
    sa.Column('projected_yield', sa.Float(), nullable=False),
    sa.Column('active_crop_count', sa.Integer(), nullable=False),
    sa.Column('active_alert_count', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_analytics_snapshots_created_at'), 'farm_analytics_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_farm_analytics_snapshots_id'), 'farm_analytics_snapshots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farm_analytics_snapshots_id'), table_name='farm_analytics_snapshots')
    op.drop_index(op.f('ix_farm_analytics_snapshots_created_at'), table_name='farm_analytics_snapshots')
    op.drop_table('farm_analytics_snapshots')
    # ### end Alembic commands ###
