"""Add weather cache table

Revision ID: 4757a891e0c1
Revises: 5a153e00c2af
Create Date: 2026-06-11 20:26:21.117684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4757a891e0c1'
down_revision: Union[str, Sequence[str], None] = '5a153e00c2af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_caches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('current_temp', sa.Float(), nullable=False),
    sa.Column('current_condition', sa.String(length=100), nullable=False),
    sa.Column('forecast_json', sa.Text(), nullable=False),
    sa.Column('cached_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_caches_id'), 'weather_caches', ['id'], unique=False)
    op.create_index(op.f('ix_weather_caches_location'), 'weather_caches', ['location'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_caches_location'), table_name='weather_caches')
    op.drop_index(op.f('ix_weather_caches_id'), table_name='weather_caches')
    op.drop_table('weather_caches')
    # ### end Alembic commands ###
