"""add_farms_table

Revision ID: 501adc0c3267
Revises: 3e3946b0e136
Create Date: 2026-06-13 07:20:46.927676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501adc0c3267'
down_revision: Union[str, Sequence[str], None] = '3e3946b0e136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('total_area_acres', sa.Float(), nullable=False),
    sa.Column('soil_type', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_id'), 'farms', ['id'], unique=False)
    op.add_column('farm_analytics_snapshots', sa.Column('farm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'farm_analytics_snapshots', 'farms', ['farm_id'], ['id'], ondelete='CASCADE')
    op.add_column('farm_plans', sa.Column('farm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'farm_plans', 'farms', ['farm_id'], ['id'], ondelete='CASCADE')
    op.add_column('farmers', sa.Column('active_farm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'farmers', 'farms', ['active_farm_id'], ['id'], ondelete='SET NULL')
    op.add_column('risk_alerts', sa.Column('farm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'risk_alerts', 'farms', ['farm_id'], ['id'], ondelete='CASCADE')
    op.add_column('soil_reports', sa.Column('farm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'soil_reports', 'farms', ['farm_id'], ['id'], ondelete='CASCADE')
    op.add_column('yield_predictions', sa.Column('farm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'yield_predictions', 'farms', ['farm_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'yield_predictions', type_='foreignkey')
    op.drop_column('yield_predictions', 'farm_id')
    op.drop_constraint(None, 'soil_reports', type_='foreignkey')
    op.drop_column('soil_reports', 'farm_id')
    op.drop_constraint(None, 'risk_alerts', type_='foreignkey')
    op.drop_column('risk_alerts', 'farm_id')
    op.drop_constraint(None, 'farmers', type_='foreignkey')
    op.drop_column('farmers', 'active_farm_id')
    op.drop_constraint(None, 'farm_plans', type_='foreignkey')
    op.drop_column('farm_plans', 'farm_id')
    op.drop_constraint(None, 'farm_analytics_snapshots', type_='foreignkey')
    op.drop_column('farm_analytics_snapshots', 'farm_id')
    op.drop_index(op.f('ix_farms_id'), table_name='farms')
    op.drop_table('farms')
    # ### end Alembic commands ###
