"""add_is_deleted_to_notifications

Revision ID: 549651001f81
Revises: d921f6d7744c
Create Date: 2026-06-12 19:42:58.862929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '549651001f81'
down_revision: Union[str, Sequence[str], None] = 'd921f6d7744c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'is_deleted')
    # ### end Alembic commands ###
