"""Add soil reports and recommendations tables

Revision ID: 5a153e00c2af
Revises: d7f9cf05ac0c
Create Date: 2026-06-11 17:56:11.165014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a153e00c2af'
down_revision: Union[str, Sequence[str], None] = 'd7f9cf05ac0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soil_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('nitrogen', sa.Float(), nullable=False),
    sa.Column('phosphorus', sa.Float(), nullable=False),
    sa.Column('potassium', sa.Float(), nullable=False),
    sa.Column('organic_matter', sa.Float(), nullable=True),
    sa.Column('crop_planned', sa.String(length=150), nullable=False),
    sa.Column('tested_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soil_reports_id'), 'soil_reports', ['id'], unique=False)
    op.create_table('soil_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('nitrogen_recommendation', sa.Text(), nullable=False),
    sa.Column('phosphorus_recommendation', sa.Text(), nullable=False),
    sa.Column('potassium_recommendation', sa.Text(), nullable=False),
    sa.Column('fertilizer_schedule', sa.Text(), nullable=False),
    sa.Column('ai_raw_analysis', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['soil_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index(op.f('ix_soil_recommendations_id'), 'soil_recommendations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soil_recommendations_id'), table_name='soil_recommendations')
    op.drop_table('soil_recommendations')
    op.drop_index(op.f('ix_soil_reports_id'), table_name='soil_reports')
    op.drop_table('soil_reports')
    # ### end Alembic commands ###
