"""add crop recommendations table

Revision ID: 71a6b6e3b37d
Revises: b527316bb6bc
Create Date: 2026-06-12 13:38:19.265077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a6b6e3b37d'
down_revision: Union[str, Sequence[str], None] = 'b527316bb6bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(length=150), nullable=False),
    sa.Column('suitability_score', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=100), nullable=False),
    sa.Column('recommendation_reason', sa.Text(), nullable=False),
    sa.Column('risk_factors', sa.Text(), nullable=False),
    sa.Column('farming_tips', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_recommendations_created_at'), 'crop_recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_crop_recommendations_id'), 'crop_recommendations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crop_recommendations_id'), table_name='crop_recommendations')
    op.drop_index(op.f('ix_crop_recommendations_created_at'), table_name='crop_recommendations')
    op.drop_table('crop_recommendations')
    # ### end Alembic commands ###
