"""add farm_planner tables

Revision ID: 924c5a522f12
Revises: 55e057a97779
Create Date: 2026-06-12 16:26:55.289567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924c5a522f12'
down_revision: Union[str, Sequence[str], None] = '55e057a97779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(length=150), nullable=False),
    sa.Column('area_acres', sa.Float(), nullable=False),
    sa.Column('planned_start_date', sa.Date(), nullable=False),
    sa.Column('expected_harvest_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_plans_id'), 'farm_plans', ['id'], unique=False)
    op.create_table('farm_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_plan_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farm_plan_id'], ['farm_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_tasks_id'), 'farm_tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farm_tasks_id'), table_name='farm_tasks')
    op.drop_table('farm_tasks')
    op.drop_index(op.f('ix_farm_plans_id'), table_name='farm_plans')
    op.drop_table('farm_plans')
    # ### end Alembic commands ###
