"""add diagnosis type to disease scans

Revision ID: b527316bb6bc
Revises: 8d07fafabd07
Create Date: 2026-06-12 07:27:42.717747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b527316bb6bc'
down_revision: Union[str, Sequence[str], None] = '8d07fafabd07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disease_scans', sa.Column('diagnosis_type', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disease_scans', 'diagnosis_type')
    # ### end Alembic commands ###
