"""add risk_alerts table

Revision ID: ccc4f3f237fe
Revises: 924c5a522f12
Create Date: 2026-06-12 17:37:06.462123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccc4f3f237fe'
down_revision: Union[str, Sequence[str], None] = '924c5a522f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(length=150), nullable=False),
    sa.Column('alert_title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('prevention_steps', sa.Text(), nullable=False),
    sa.Column('monitoring_advice', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_alerts_created_at'), 'risk_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_alerts_id'), 'risk_alerts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_alerts_id'), table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_created_at'), table_name='risk_alerts')
    op.drop_table('risk_alerts')
    # ### end Alembic commands ###
