"""add consultation_history table

Revision ID: f738b85acdbd
Revises: ccc4f3f237fe
Create Date: 2026-06-12 18:05:01.327237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f738b85acdbd'
down_revision: Union[str, Sequence[str], None] = 'ccc4f3f237fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('context_snapshot_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_history_created_at'), 'consultation_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_consultation_history_id'), 'consultation_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultation_history_id'), table_name='consultation_history')
    op.drop_index(op.f('ix_consultation_history_created_at'), table_name='consultation_history')
    op.drop_table('consultation_history')
    # ### end Alembic commands ###
